"""update field name in custom ai

Revision ID: 5d69942c6171
Revises: f660dfc0f669
Create Date: 2025-05-04 17:19:58.789191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d69942c6171'
down_revision = 'f660dfc0f669'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_ai', sa.Column('ai_model', sa.String(length=255), nullable=True))
    op.drop_column('custom_ai', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_ai', sa.Column('model', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('custom_ai', 'ai_model')
    # ### end Alembic commands ###
