"""added default model

Revision ID: 1a592c92fb37
Revises: 5d69942c6171
Create Date: 2025-05-04 17:25:55.217115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a592c92fb37'
down_revision = '5d69942c6171'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First set default value for existing NULL values
    op.execute("UPDATE custom_ai SET ai_model = 'mistralai/Mistral-7B-Instruct-v0.3' WHERE ai_model IS NULL")
    
    # Then alter the column to be NOT NULL with DEFAULT
    op.alter_column('custom_ai', 'ai_model',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               server_default=sa.text("'mistralai/Mistral-7B-Instruct-v0.3'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_ai', 'ai_model',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               server_default=None)
    # ### end Alembic commands ###