"""modified intpk to uuidpk

Revision ID: 496881e8dde4
Revises: 
Create Date: 2025-05-03 13:23:11.532880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496881e8dde4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_ai',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('knowledge_base',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_ai_id', sa.UUID(), nullable=False),
    sa.Column('update_version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['custom_ai_id'], ['custom_ai.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personality',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('custom_ai_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['custom_ai_id'], ['custom_ai.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_ai_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personality')
    op.drop_table('knowledge_base')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('custom_ai')
    # ### end Alembic commands ###
