"""added custom ai, knowledge and personality models

Revision ID: f8b41fbb55eb
Revises: 5f52fa8831d8
Create Date: 2025-05-01 23:47:35.252280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b41fbb55eb'
down_revision = '5f52fa8831d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_ai',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_ai_id'), 'custom_ai', ['id'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('custom_ai_id', sa.Integer(), nullable=False),
    sa.Column('update_version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['custom_ai_id'], ['custom_ai.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_id'), 'knowledge_base', ['id'], unique=False)
    op.create_table('personality',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('custom_ai_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['custom_ai_id'], ['custom_ai.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_ai_id')
    )
    op.create_index(op.f('ix_personality_id'), 'personality', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personality_id'), table_name='personality')
    op.drop_table('personality')
    op.drop_index(op.f('ix_knowledge_base_id'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index(op.f('ix_custom_ai_id'), table_name='custom_ai')
    op.drop_table('custom_ai')
    # ### end Alembic commands ###
